app:
  name: 'order-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5002

postgres:
  pool_max: 2
  dsn_url: host=47.109.29.98 port=5432 user=postgres password=rc123321 dbname=postgres sslmode=disable

logger:
  log_level: 'debug'
  rollbar_env: 'order-service'