app:
  name: 'order-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5002

  
mysql8:
  pool_max: 100
  idle_conn_max: 50
  max_idle_time: 86400
  dsn_url: root:123456@tcp(127.0.0.1:3306)/ddd_go?charset=utf8mb4&parseTime=True


logger:
  log_level: 'debug'
  rollbar_env: 'order-service'
