// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"google.golang.org/grpc"
	"myshop/cmd/order/config"
	"myshop/internal/order/app/router"
	"myshop/internal/order/infras/repo"
	"myshop/internal/order/usecases/order"
	"myshop/pkg/mysql8"
	"myshop/pkg/postgres"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, dbPGConnStr postgres.DBConnString, dbMysql8ConnStr mysql8.DBConnString, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbMysql8EngineFunc(dbMysql8ConnStr)
	if err != nil {
		return nil, nil, err
	}
	orderRepo := repo.NewOrderRepo(dbEngine)
	useCase := order.NewService(orderRepo)
	postgresDBEngine, cleanup2, err := dbPGEngineFunc(dbPGConnStr)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	orderServiceServer := router.NewOrderGRPCServer(grpcServer, useCase)
	app := New(cfg, useCase, postgresDBEngine, dbEngine, orderServiceServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbPGEngineFunc(url postgres.DBConnString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}

func dbMysql8EngineFunc(url mysql8.DBConnString) (mysql8.DBEngine, func(), error) {
	db, err := mysql8.NewMysql8DB(url)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}
