// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"google.golang.org/grpc"
	"myshop/cmd/order/config"
	"myshop/internal/order/app/router"
	"myshop/internal/order/infras/repo"
	"myshop/internal/order/usecases/order"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, grpcServer *grpc.Server) (*App, error) {
	orderRepo := repo.NewOrderRepo()
	useCase := order.NewService(orderRepo)
	orderServiceServer := router.NewOrderGRPCServer(grpcServer, useCase)
	app := New(cfg, useCase, orderServiceServer)
	return app, nil
}
