app:
  name: 'reverse-proxy'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5000

grpc:
  user_host: '0.0.0.0'
  user_port: 5001
  order_host: '0.0.0.0'
  order_port: 5002

logger:
  log_level: 'debug'
  rollbar_env: 'reverse-proxy'